spring.main.web-environment=false

#facebook
facebook.url=https://www.facebook.com/search/top/?q=%s

#postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.data-class-name=postgres.Driver

